# Generated by Django 3.2.9 on 2021-12-27 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GalasJob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя валюты')),
                ('price', models.PositiveBigIntegerField(verbose_name='Цена валюты')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GalasJob.category', verbose_name='Тип валюты')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
    ]
