# Generated by Django 3.2.9 on 2021-12-27 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GalasJob', '0002_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Тип валюты', 'verbose_name_plural': 'Типы валюты'},
        ),
        migrations.CreateModel(
            name='CurrencyImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img', verbose_name='Изображение валюты')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GalasJob.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Изображение валюты',
                'verbose_name_plural': 'Изображения валюты',
            },
        ),
    ]
