# Generated by Django 3.2.9 on 2021-12-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPTRIX_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default='Мужской', max_length=7),
        ),
    ]
